CFLAG = -Wall -std=c++11
BIN   = vector1 deque1 array1 list1

all: $(BIN)

list1 : list1.cpp
	g++ $(CFLAG) $^ -o $@

array1 : array1.cpp
	g++ $(CFLAG) $^ -o $@

vector1 : vector1.cpp
	g++ $(CFLAG) $^ -o $@

deque1 : deque1.cpp
	g++ $(CFLAG) $^ -o $@
